name: Staging Deploy to ECS on PR Comment
description: "Work only for PR comments"
inputs:
  github_token:
    description: Github token to write comments on PR. Commonly secrets.GITHUB_TOKEN
    required: true
  match_comment_to_deploy:
    description: String that will look for in the PR
    required: false
    default: '@meetlara/deploy'
  aws_access_key_id:
    description: AWS Key ID
    required: true
  aws_secret_access_key:
    description: AWS Secret Access Key
    required: true
  ecr_image_name:
    description: Define the name of the ECR image registry
    required: true
  task_definition_contianer_name:
    description: Define the name of the container in the Task Definition
    required: true
  ecs_service_name:
    description: Define the name of the ECS Service
    required: true
  ecs_cluster_name:
    description: Define the name of the ECS Cluster
    required: true
  task_definition_path:
    description: Define the path to the Task Definition
    required: true
  working_directory:
    description: Define the path of working dir
    required: false
    default: ./api
runs:
  using: "composite"
  steps:
    - name: Check if @meetlara/deploy is on the message
      uses: khan/pull-request-comment-trigger@master
      id: check
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        trigger: ${{ inputs.match_comment_to_deploy }}
        prefix_only: true
        reaction: 'rocket'

    - name: Checkout
      if: steps.check.outputs.triggered == 'true'
      uses: actions/checkout@v2
    
    - name: Checkout Pull Request
      shell: bash
      id: commit
      if: steps.check.outputs.triggered == 'true'
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        hub pr checkout ${{ github.event.issue.number }}
        echo "::set-output name=sha::$(git rev-parse HEAD)"

    - name: Deploy to ECS
      if: steps.check.outputs.triggered == 'true'
      uses: meetlara/ecs-deploy@main
      with:
        aws_access_key_id: ${{ inputs.aws_access_key_id }}
        aws_secret_access_key: ${{ inputs.aws_secret_access_key }}
        ecr_image_name: ${{ inputs.ecr_image_name }}
        ecr_image_tag: ${{ steps.commit.outputs.sha }}
        task_definition_contianer_name: ${{ inputs.task_definition_contianer_name }}
        ecs_service_name: ${{ inputs.ecs_service_name }}
        ecs_cluster_name: ${{ inputs.ecs_cluster_name }}
        task_definition_path: ${{ inputs.task_definition_path }}
        working_directory: ${{ inputs.working_directory }}

    - name: Message success
      if: ${{ steps.check.outputs.triggered == 'true' && success() }}
      uses: actions/github-script@v4
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Deployment succeeded! 🚀\n\nYou can check the deploy logs [here](https://github.com/' + context.repo.owner + '/' + context.repo.repo + '/actions/runs/' + context.runId + ')\n\nRemember, it\'s not deployed yet. AWS is doing some magic and in 2 mins it will be available 😄',
          });
      
    - name: Message failure
      if: ${{ steps.check.outputs.triggered == 'true' && failure() }}
      uses: actions/github-script@v4
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Deployment failed! ❌\n\nYou can check errors on deploy logs [here](https://github.com/' + context.repo.owner + '/' + context.repo.repo + '/actions/runs/' + context.runId + ')',
          });
